# -*- coding: utf-8 -*-
"""00_intro_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muR96EcN_uLN_syxlrOOOZdQPRK4atCa

'''
Program: 01 add_two_numbers
--------------------
This program asks the
user for two integers and prints their sum.
'''
"""

def main():
    print("This program Adds two Numbers.")

    # Prompt and convert first number
    num1 = int(input("Enter the first number: "))

    # Prompt and convert second number
    num2 = int(input("Enter the second number: "))

    # Calculate and display the sum
    total = num1 + num2
    print("The total is " + str(total) + ".")


if __name__ == '__main__':
    main()

"""'''
Program: 02 favorite_animal_bot
----------------------------
This program asks the user what their favorite animal is,
and responds by saying that it's the program's favorite too!
'''
"""

def bot():
    print("This program an Agreement Bot.")

    animal = str(input("What's your favorite animal? "))
    print(f'My favourite animal is also {animal}!')

if __name__ == '__main__':
    bot()

"""'''
Program: 03 fahrenheit_to_celsius
------------------------------
This program prompts the user for a temperature
in Fahrenheit and converts it to Celsius.
'''
"""

def temp():
    print("This program converts Fahrenheit to Celsius.")

    # Prompt the user for input
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))

    # Convert to Celsius using the correct formula
    celsius = (fahrenheit - 32) * 5.0 / 9.0

    # Output the result
    print("Temperature:", str(fahrenheit) + "F =", str(celsius) + "C")

if __name__ == '__main__':
    temp()

"""'''
Program: 04 age_riddle_solver
--------------------------
This program solves an age-related riddle involving five friends:
Anton, Beth, Chen, Drew, and Ethan. It calculates each person's
age based on given relationships and prints the results.
'''
"""

def add_ages():
    print("This program solves an age-related riddle!")

    # Assigning ages based on the riddle
    Anton: int = 21
    Beth: int = Anton + 6
    Chen: int = Beth + 20
    Drew: int = Chen + Anton
    Ethan: int = Chen

    # Printing the results
    print("Anton is " + str(Anton) + ".")
    print("Beth is " + str(Beth) + ".")
    print("Chen is " + str(Chen) + ".")
    print("Drew is " + str(Drew) + ".")
    print("Ethan is " + str(Ethan) + ".")

if __name__ == '__main__':
    add_ages()

"""'''
Program: 05 triangle_perimeter_calculator
--------------------------------------
This program prompts the user to enter the lengths of the
three sides of a triangle, calculates the perimeter, and
prints the result.
'''
"""

def tri_perimenter():
    print("This program calculates the Perimeter of a Triangle.")

    # Get the 3 side lengths of the triangle from the user
    side1: float = float(input("What is the length of side 1? "))
    side2: float = float(input("What is the length of side 2? "))
    side3: float = float(input("What is the length of side 3? "))

    # Calculate perimeter
    perimeter:float = side1 + side2 + side3

    # Print the perimeter (rounded to 2 decimal places)
    print("The perimeter of the triangle is " + str(round(perimeter, 2)))

if __name__ == '__main__':
    tri_perimenter()

"""'''
Program: 06 square_calculator
--------------------------
This program asks the user for a number and prints its square.
""
"""

def square_number():
    print("This program calculates the Square of a Number.")

    # Get the user's number
    number: float = float(input("Type a number to see its square: "))

    # Calculate and print the square
    print(f"{number} squared is {number ** 2}")

if __name__ == '__main__':
    square_number()